// <auto-generated>
// Generated by eng/gen-browser-events.py from src/CC.CSX/HtmlAttributeKeys_Events.cs.
// Do not edit by hand — regenerate instead.
// </auto-generated>
using System;
using System.Threading.Tasks;
using CC.CSX;

namespace CC.CSX.Browser;

public static partial class HtmlEvents
{
    ///<summary>Handles the 'blur' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onBlur(Action handler) => Bind("blur", handler);

    ///<summary>Handles the 'blur' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onBlur(Action<DomEvent> handler) => Bind("blur", handler);

    ///<summary>Handles the 'blur' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onBlur(Func<Task> handler) => Bind("blur", handler);

    ///<summary>Handles the 'blur' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onBlur(Func<DomEvent, Task> handler) => Bind("blur", handler);

    ///<summary>Handles the 'change' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onChange(Action handler) => Bind("change", handler);

    ///<summary>Handles the 'change' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onChange(Action<DomEvent> handler) => Bind("change", handler);

    ///<summary>Handles the 'change' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onChange(Func<Task> handler) => Bind("change", handler);

    ///<summary>Handles the 'change' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onChange(Func<DomEvent, Task> handler) => Bind("change", handler);

    ///<summary>Handles the 'contextmenu' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onContextmenu(Action handler) => Bind("contextmenu", handler);

    ///<summary>Handles the 'contextmenu' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onContextmenu(Action<DomEvent> handler) => Bind("contextmenu", handler);

    ///<summary>Handles the 'contextmenu' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onContextmenu(Func<Task> handler) => Bind("contextmenu", handler);

    ///<summary>Handles the 'contextmenu' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onContextmenu(Func<DomEvent, Task> handler) => Bind("contextmenu", handler);

    ///<summary>Handles the 'focus' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onFocus(Action handler) => Bind("focus", handler);

    ///<summary>Handles the 'focus' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onFocus(Action<DomEvent> handler) => Bind("focus", handler);

    ///<summary>Handles the 'focus' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onFocus(Func<Task> handler) => Bind("focus", handler);

    ///<summary>Handles the 'focus' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onFocus(Func<DomEvent, Task> handler) => Bind("focus", handler);

    ///<summary>Handles the 'input' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInput(Action handler) => Bind("input", handler);

    ///<summary>Handles the 'input' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInput(Action<DomEvent> handler) => Bind("input", handler);

    ///<summary>Handles the 'input' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInput(Func<Task> handler) => Bind("input", handler);

    ///<summary>Handles the 'input' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInput(Func<DomEvent, Task> handler) => Bind("input", handler);

    ///<summary>Handles the 'invalid' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInvalid(Action handler) => Bind("invalid", handler);

    ///<summary>Handles the 'invalid' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInvalid(Action<DomEvent> handler) => Bind("invalid", handler);

    ///<summary>Handles the 'invalid' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInvalid(Func<Task> handler) => Bind("invalid", handler);

    ///<summary>Handles the 'invalid' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onInvalid(Func<DomEvent, Task> handler) => Bind("invalid", handler);

    ///<summary>Handles the 'reset' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onReset(Action handler) => Bind("reset", handler);

    ///<summary>Handles the 'reset' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onReset(Action<DomEvent> handler) => Bind("reset", handler);

    ///<summary>Handles the 'reset' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onReset(Func<Task> handler) => Bind("reset", handler);

    ///<summary>Handles the 'reset' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onReset(Func<DomEvent, Task> handler) => Bind("reset", handler);

    ///<summary>Handles the 'search' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSearch(Action handler) => Bind("search", handler);

    ///<summary>Handles the 'search' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSearch(Action<DomEvent> handler) => Bind("search", handler);

    ///<summary>Handles the 'search' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSearch(Func<Task> handler) => Bind("search", handler);

    ///<summary>Handles the 'search' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSearch(Func<DomEvent, Task> handler) => Bind("search", handler);

    ///<summary>Handles the 'select' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSelect(Action handler) => Bind("select", handler);

    ///<summary>Handles the 'select' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSelect(Action<DomEvent> handler) => Bind("select", handler);

    ///<summary>Handles the 'select' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSelect(Func<Task> handler) => Bind("select", handler);

    ///<summary>Handles the 'select' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSelect(Func<DomEvent, Task> handler) => Bind("select", handler);

    ///<summary>Handles the 'submit' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSubmit(Action handler) => Bind("submit", handler);

    ///<summary>Handles the 'submit' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSubmit(Action<DomEvent> handler) => Bind("submit", handler);

    ///<summary>Handles the 'submit' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSubmit(Func<Task> handler) => Bind("submit", handler);

    ///<summary>Handles the 'submit' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onSubmit(Func<DomEvent, Task> handler) => Bind("submit", handler);

    ///<summary>Handles the 'keydown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeydown(Action handler) => Bind("keydown", handler);

    ///<summary>Handles the 'keydown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeydown(Action<DomEvent> handler) => Bind("keydown", handler);

    ///<summary>Handles the 'keydown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeydown(Func<Task> handler) => Bind("keydown", handler);

    ///<summary>Handles the 'keydown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeydown(Func<DomEvent, Task> handler) => Bind("keydown", handler);

    ///<summary>Handles the 'keypress' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeypress(Action handler) => Bind("keypress", handler);

    ///<summary>Handles the 'keypress' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeypress(Action<DomEvent> handler) => Bind("keypress", handler);

    ///<summary>Handles the 'keypress' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeypress(Func<Task> handler) => Bind("keypress", handler);

    ///<summary>Handles the 'keypress' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeypress(Func<DomEvent, Task> handler) => Bind("keypress", handler);

    ///<summary>Handles the 'keyup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeyup(Action handler) => Bind("keyup", handler);

    ///<summary>Handles the 'keyup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeyup(Action<DomEvent> handler) => Bind("keyup", handler);

    ///<summary>Handles the 'keyup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeyup(Func<Task> handler) => Bind("keyup", handler);

    ///<summary>Handles the 'keyup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onKeyup(Func<DomEvent, Task> handler) => Bind("keyup", handler);

    ///<summary>Handles the 'click' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onClick(Action handler) => Bind("click", handler);

    ///<summary>Handles the 'click' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onClick(Action<DomEvent> handler) => Bind("click", handler);

    ///<summary>Handles the 'click' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onClick(Func<Task> handler) => Bind("click", handler);

    ///<summary>Handles the 'click' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onClick(Func<DomEvent, Task> handler) => Bind("click", handler);

    ///<summary>Handles the 'dblclick' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDblclick(Action handler) => Bind("dblclick", handler);

    ///<summary>Handles the 'dblclick' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDblclick(Action<DomEvent> handler) => Bind("dblclick", handler);

    ///<summary>Handles the 'dblclick' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDblclick(Func<Task> handler) => Bind("dblclick", handler);

    ///<summary>Handles the 'dblclick' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDblclick(Func<DomEvent, Task> handler) => Bind("dblclick", handler);

    ///<summary>Handles the 'mousedown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousedown(Action handler) => Bind("mousedown", handler);

    ///<summary>Handles the 'mousedown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousedown(Action<DomEvent> handler) => Bind("mousedown", handler);

    ///<summary>Handles the 'mousedown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousedown(Func<Task> handler) => Bind("mousedown", handler);

    ///<summary>Handles the 'mousedown' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousedown(Func<DomEvent, Task> handler) => Bind("mousedown", handler);

    ///<summary>Handles the 'mousemove' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousemove(Action handler) => Bind("mousemove", handler);

    ///<summary>Handles the 'mousemove' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousemove(Action<DomEvent> handler) => Bind("mousemove", handler);

    ///<summary>Handles the 'mousemove' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousemove(Func<Task> handler) => Bind("mousemove", handler);

    ///<summary>Handles the 'mousemove' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousemove(Func<DomEvent, Task> handler) => Bind("mousemove", handler);

    ///<summary>Handles the 'mouseout' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseout(Action handler) => Bind("mouseout", handler);

    ///<summary>Handles the 'mouseout' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseout(Action<DomEvent> handler) => Bind("mouseout", handler);

    ///<summary>Handles the 'mouseout' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseout(Func<Task> handler) => Bind("mouseout", handler);

    ///<summary>Handles the 'mouseout' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseout(Func<DomEvent, Task> handler) => Bind("mouseout", handler);

    ///<summary>Handles the 'mouseover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseover(Action handler) => Bind("mouseover", handler);

    ///<summary>Handles the 'mouseover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseover(Action<DomEvent> handler) => Bind("mouseover", handler);

    ///<summary>Handles the 'mouseover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseover(Func<Task> handler) => Bind("mouseover", handler);

    ///<summary>Handles the 'mouseover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseover(Func<DomEvent, Task> handler) => Bind("mouseover", handler);

    ///<summary>Handles the 'mouseup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseup(Action handler) => Bind("mouseup", handler);

    ///<summary>Handles the 'mouseup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseup(Action<DomEvent> handler) => Bind("mouseup", handler);

    ///<summary>Handles the 'mouseup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseup(Func<Task> handler) => Bind("mouseup", handler);

    ///<summary>Handles the 'mouseup' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMouseup(Func<DomEvent, Task> handler) => Bind("mouseup", handler);

    ///<summary>Handles the 'mousewheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousewheel(Action handler) => Bind("mousewheel", handler);

    ///<summary>Handles the 'mousewheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousewheel(Action<DomEvent> handler) => Bind("mousewheel", handler);

    ///<summary>Handles the 'mousewheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousewheel(Func<Task> handler) => Bind("mousewheel", handler);

    ///<summary>Handles the 'mousewheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onMousewheel(Func<DomEvent, Task> handler) => Bind("mousewheel", handler);

    ///<summary>Handles the 'wheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onWheel(Action handler) => Bind("wheel", handler);

    ///<summary>Handles the 'wheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onWheel(Action<DomEvent> handler) => Bind("wheel", handler);

    ///<summary>Handles the 'wheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onWheel(Func<Task> handler) => Bind("wheel", handler);

    ///<summary>Handles the 'wheel' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onWheel(Func<DomEvent, Task> handler) => Bind("wheel", handler);

    ///<summary>Handles the 'drag' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrag(Action handler) => Bind("drag", handler);

    ///<summary>Handles the 'drag' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrag(Action<DomEvent> handler) => Bind("drag", handler);

    ///<summary>Handles the 'drag' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrag(Func<Task> handler) => Bind("drag", handler);

    ///<summary>Handles the 'drag' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrag(Func<DomEvent, Task> handler) => Bind("drag", handler);

    ///<summary>Handles the 'dragend' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragend(Action handler) => Bind("dragend", handler);

    ///<summary>Handles the 'dragend' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragend(Action<DomEvent> handler) => Bind("dragend", handler);

    ///<summary>Handles the 'dragend' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragend(Func<Task> handler) => Bind("dragend", handler);

    ///<summary>Handles the 'dragend' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragend(Func<DomEvent, Task> handler) => Bind("dragend", handler);

    ///<summary>Handles the 'dragenter' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragenter(Action handler) => Bind("dragenter", handler);

    ///<summary>Handles the 'dragenter' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragenter(Action<DomEvent> handler) => Bind("dragenter", handler);

    ///<summary>Handles the 'dragenter' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragenter(Func<Task> handler) => Bind("dragenter", handler);

    ///<summary>Handles the 'dragenter' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragenter(Func<DomEvent, Task> handler) => Bind("dragenter", handler);

    ///<summary>Handles the 'dragleave' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragleave(Action handler) => Bind("dragleave", handler);

    ///<summary>Handles the 'dragleave' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragleave(Action<DomEvent> handler) => Bind("dragleave", handler);

    ///<summary>Handles the 'dragleave' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragleave(Func<Task> handler) => Bind("dragleave", handler);

    ///<summary>Handles the 'dragleave' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragleave(Func<DomEvent, Task> handler) => Bind("dragleave", handler);

    ///<summary>Handles the 'dragover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragover(Action handler) => Bind("dragover", handler);

    ///<summary>Handles the 'dragover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragover(Action<DomEvent> handler) => Bind("dragover", handler);

    ///<summary>Handles the 'dragover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragover(Func<Task> handler) => Bind("dragover", handler);

    ///<summary>Handles the 'dragover' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragover(Func<DomEvent, Task> handler) => Bind("dragover", handler);

    ///<summary>Handles the 'dragstart' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragstart(Action handler) => Bind("dragstart", handler);

    ///<summary>Handles the 'dragstart' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragstart(Action<DomEvent> handler) => Bind("dragstart", handler);

    ///<summary>Handles the 'dragstart' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragstart(Func<Task> handler) => Bind("dragstart", handler);

    ///<summary>Handles the 'dragstart' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDragstart(Func<DomEvent, Task> handler) => Bind("dragstart", handler);

    ///<summary>Handles the 'drop' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrop(Action handler) => Bind("drop", handler);

    ///<summary>Handles the 'drop' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrop(Action<DomEvent> handler) => Bind("drop", handler);

    ///<summary>Handles the 'drop' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrop(Func<Task> handler) => Bind("drop", handler);

    ///<summary>Handles the 'drop' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onDrop(Func<DomEvent, Task> handler) => Bind("drop", handler);

    ///<summary>Handles the 'scroll' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onScroll(Action handler) => Bind("scroll", handler);

    ///<summary>Handles the 'scroll' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onScroll(Action<DomEvent> handler) => Bind("scroll", handler);

    ///<summary>Handles the 'scroll' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onScroll(Func<Task> handler) => Bind("scroll", handler);

    ///<summary>Handles the 'scroll' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onScroll(Func<DomEvent, Task> handler) => Bind("scroll", handler);

    ///<summary>Handles the 'copy' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCopy(Action handler) => Bind("copy", handler);

    ///<summary>Handles the 'copy' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCopy(Action<DomEvent> handler) => Bind("copy", handler);

    ///<summary>Handles the 'copy' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCopy(Func<Task> handler) => Bind("copy", handler);

    ///<summary>Handles the 'copy' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCopy(Func<DomEvent, Task> handler) => Bind("copy", handler);

    ///<summary>Handles the 'cut' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCut(Action handler) => Bind("cut", handler);

    ///<summary>Handles the 'cut' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCut(Action<DomEvent> handler) => Bind("cut", handler);

    ///<summary>Handles the 'cut' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCut(Func<Task> handler) => Bind("cut", handler);

    ///<summary>Handles the 'cut' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onCut(Func<DomEvent, Task> handler) => Bind("cut", handler);

    ///<summary>Handles the 'paste' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onPaste(Action handler) => Bind("paste", handler);

    ///<summary>Handles the 'paste' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onPaste(Action<DomEvent> handler) => Bind("paste", handler);

    ///<summary>Handles the 'paste' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onPaste(Func<Task> handler) => Bind("paste", handler);

    ///<summary>Handles the 'paste' DOM event with a .NET handler.</summary>
    public static HtmlAttribute onPaste(Func<DomEvent, Task> handler) => Bind("paste", handler);
}
