using System.Collections.Generic;
using System.Text;

namespace CC.CSX.RenderPlan.Generator;

/// <summary>
/// Emits an optimized builder per [RenderOptimized] method: <c>&lt;Type&gt;__Optimized.&lt;Method&gt;(args)</c>
/// returns a <see cref="PlanNode"/> whose render writes baked static byte segments (memcpy) plus the
/// dynamic holes/loops/conditionals. The signature matches the original (returns HtmlNode), so an
/// interceptor can redirect call sites to it.
/// </summary>
internal static class CodeEmitter
{
    public static string EmitType(string ns, string typeName, List<MethodPlan> methods)
    {
        var consts = new StringBuilder();
        var body = new StringBuilder();
        int constId = 0;

        foreach (var m in methods)
        {
            if (m.Plan is null) continue;
            var pars = string.Join(", ", m.Params.ConvertAll(p => $"{p.Type} {p.Name}"));

            body.AppendLine($"    /// <summary>Optimized render plan for {Escape(m.Signature)}.</summary>");
            body.AppendLine($"    public static global::CC.CSX.HtmlNode {m.MethodName}({pars})");
            body.AppendLine("        => new global::CC.CSX.PlanNode(__tw =>");
            body.AppendLine("        {");
            EmitSegs(m.Plan, m.MethodName, body, consts, ref constId, "            ");
            body.AppendLine("        });");
            body.AppendLine();
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> CC.CSX.RenderPlan.Generator");
        sb.AppendLine("#nullable enable");
        bool hasNs = !string.IsNullOrEmpty(ns);
        if (hasNs) sb.AppendLine($"namespace {ns}").AppendLine("{");
        sb.AppendLine($"internal static class {typeName}__Optimized");
        sb.AppendLine("{");
        sb.Append(consts);
        if (consts.Length > 0) sb.AppendLine();
        sb.Append(body);
        sb.AppendLine("}");
        if (hasNs) sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitSegs(List<Segment> segs, string method, StringBuilder body, StringBuilder consts, ref int id, string indent)
    {
        foreach (var seg in segs)
        {
            switch (seg)
            {
                case StaticSeg st:
                    string sField = $"_{method}_S{id}";
                    string bField = $"_{method}_B{id}";
                    id++;
                    consts.AppendLine($"    private static readonly string {sField} = \"{Escape(st.Text)}\";");
                    consts.AppendLine($"    private static readonly byte[] {bField} = global::System.Text.Encoding.UTF8.GetBytes({sField});");
                    body.AppendLine($"{indent}global::CC.CSX.PlanStatics.WriteStatic(__tw, {bField}, {sField});");
                    break;
                case HoleSeg h: EmitWrite(h.Expr, h.Kind, body, indent); break;
                case OpaqueSeg op: EmitWrite(op.Expr, op.Kind, body, indent); break;
                case LoopSeg loop:
                    body.AppendLine($"{indent}foreach (var {loop.ItemVar} in ({loop.Items}))");
                    body.AppendLine($"{indent}{{");
                    EmitSegs(loop.Body, method, body, consts, ref id, indent + "    ");
                    body.AppendLine($"{indent}}}");
                    break;
                case CondSeg cond:
                    body.AppendLine($"{indent}if ({cond.Cond})");
                    body.AppendLine($"{indent}{{");
                    EmitSegs(cond.Then, method, body, consts, ref id, indent + "    ");
                    body.AppendLine($"{indent}}}");
                    body.AppendLine($"{indent}else");
                    body.AppendLine($"{indent}{{");
                    EmitSegs(cond.Else, method, body, consts, ref id, indent + "    ");
                    body.AppendLine($"{indent}}}");
                    break;
            }
        }
    }

    static void EmitWrite(string expr, WriteKind kind, StringBuilder body, string indent)
    {
        switch (kind)
        {
            case WriteKind.Text:
                body.AppendLine($"{indent}__tw.Write({expr});");
                break;
            case WriteKind.Value:
                body.AppendLine($"{indent}__tw.Write(({expr}).ToString());");
                break;
            case WriteKind.Node:
                body.AppendLine($"{indent}{{ var __n = ({expr}); if (__n is not null) {{ global::System.IO.TextWriter __t = __tw; ((global::CC.CSX.HtmlItem)__n).WriteTo(ref __t); }} }}");
                break;
        }
    }

    static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        foreach (char c in s)
            sb.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => c.ToString(),
            });
        return sb.ToString();
    }
}
