using System.Collections.Generic;
using System.Text;

namespace CC.CSX.RenderPlan.Generator;

/// <summary>
/// Emits an optimized writer per [RenderOptimized] method: static runs become baked UTF-8 byte
/// constants written by memcpy, and only the dynamic holes/loops are evaluated. Generated as a
/// standalone <c>&lt;Type&gt;__Optimized</c> static class (no interceptors yet).
/// </summary>
internal static class CodeEmitter
{
    public static string EmitType(string ns, string typeName, List<MethodPlan> methods)
    {
        var consts = new StringBuilder();
        var body = new StringBuilder();
        int constId = 0;

        foreach (var m in methods)
        {
            if (m.Plan is null) continue;

            var pars = string.Join(", ", m.Params.ConvertAll(p => $"{p.Type} {p.Name}"));
            if (pars.Length > 0) pars += ", ";
            body.AppendLine($"    /// <summary>Optimized render plan for {Escape(m.Signature)}.</summary>");
            body.AppendLine($"    public static void {m.MethodName}({pars}global::System.Buffers.IBufferWriter<byte> output)");
            body.AppendLine("    {");
            body.AppendLine("        using var w = new global::CC.CSX.Utf8HtmlWriter(output);");
            EmitSegs(m.Plan, m.MethodName, body, consts, ref constId, "        ");
            body.AppendLine("    }");
            body.AppendLine();
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> CC.CSX.RenderPlan.Generator");
        sb.AppendLine("#nullable enable");
        bool hasNs = !string.IsNullOrEmpty(ns);
        if (hasNs) sb.AppendLine($"namespace {ns}").AppendLine("{");
        sb.AppendLine($"internal static class {typeName}__Optimized");
        sb.AppendLine("{");
        sb.Append(consts);
        if (consts.Length > 0) sb.AppendLine();
        sb.Append(body);
        sb.AppendLine("}");
        if (hasNs) sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitSegs(List<Segment> segs, string method, StringBuilder body, StringBuilder consts, ref int id, string indent)
    {
        foreach (var seg in segs)
        {
            switch (seg)
            {
                case StaticSeg st:
                    string field = $"_{method}_S{id++}";
                    consts.AppendLine($"    private static readonly byte[] {field} = global::System.Text.Encoding.UTF8.GetBytes(\"{Escape(st.Text)}\");");
                    body.AppendLine($"{indent}w.WriteRawUtf8({field});");
                    break;
                case HoleSeg h:
                    EmitWrite(h.Expr, h.Kind, body, indent);
                    break;
                case OpaqueSeg op:
                    EmitWrite(op.Expr, op.Kind, body, indent);
                    break;
                case LoopSeg loop:
                    body.AppendLine($"{indent}foreach (var {loop.ItemVar} in ({loop.Items}))");
                    body.AppendLine($"{indent}{{");
                    EmitSegs(loop.Body, method, body, consts, ref id, indent + "    ");
                    body.AppendLine($"{indent}}}");
                    break;
            }
        }
    }

    static void EmitWrite(string expr, WriteKind kind, StringBuilder body, string indent)
    {
        switch (kind)
        {
            case WriteKind.Text:
                body.AppendLine($"{indent}w.Write({expr});");
                break;
            case WriteKind.Value:
                body.AppendLine($"{indent}w.Write(({expr}).ToString());");
                break;
            case WriteKind.Node:
                body.AppendLine($"{indent}{{ var __n = ({expr}); if (__n is not null) {{ global::System.IO.TextWriter __tw = w; ((global::CC.CSX.HtmlItem)__n).WriteTo(ref __tw); }} }}");
                break;
        }
    }

    static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        foreach (char c in s)
            sb.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => c.ToString(),
            });
        return sb.ToString();
    }
}
