using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CC.CSX.RenderPlan.Generator;

internal sealed class CallSite(string attr, string ns, string typeName, string method, string returnType, List<string> paramTypes)
{
    public string Attr { get; } = attr;
    public string Namespace { get; } = ns;
    public string TypeName { get; } = typeName;
    public string Method { get; } = method;
    public string ReturnType { get; } = returnType;
    public List<string> ParamTypes { get; } = paramTypes;
    public string Key => $"{Namespace}|{TypeName}|{Method}|{string.Join(",", ParamTypes)}";
}

/// <summary>
/// Emits C# interceptors that redirect each call site of a [RenderOptimized] method to the matching
/// &lt;Type&gt;__Optimized builder. The interceptor shares the original signature (returns HtmlNode),
/// so the swap is transparent to callers. Requires the consumer to enable interceptors for the
/// "CC.CSX.Generated" namespace.
/// </summary>
internal static class InterceptorEmitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<CallSite?> sites)
    {
        var groups = sites.Where(s => s is not null).Select(s => s!).GroupBy(s => s.Key).ToList();
        if (groups.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> CC.CSX.RenderPlan.Generator — interceptors");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace CC.CSX.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    file static class RenderPlanInterceptors");
        sb.AppendLine("    {");

        int n = 0;
        foreach (var group in groups)
        {
            var s = group.First();
            string optTarget = string.IsNullOrEmpty(s.Namespace)
                ? $"global::{s.TypeName}__Optimized"
                : $"global::{s.Namespace}.{s.TypeName}__Optimized";
            string pars = string.Join(", ", s.ParamTypes.Select((t, i) => $"{t} p{i}"));
            string args = string.Join(", ", Enumerable.Range(0, s.ParamTypes.Count).Select(i => $"p{i}"));

            foreach (var site in group) sb.AppendLine($"        {site.Attr}");
            sb.AppendLine($"        public static {s.ReturnType} Intercept_{s.Method}_{n}({pars})");
            sb.AppendLine($"            => {optTarget}.{s.Method}({args});");
            sb.AppendLine();
            n++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // the version-based InterceptsLocationAttribute is recognized by full name; define it here
        // since the targeted framework does not ship it.
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("RenderPlan.Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
