using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CC.CSX.RenderPlan.Generator;

/// <summary>
/// SPIKE: finds [RenderOptimized] methods and reports the static/dynamic render-plan decomposition
/// it infers (no codegen / interceptors yet). It models the built-in CC.CSX pure factories by their
/// known rendering, inlines user [HtmlPure]/[RenderOptimized] methods, turns Select/Each into loops,
/// and consolidates adjacent static segments. Output is emitted as a comment in a .g.cs file and as
/// info diagnostics, so the segmentation can be inspected on real views.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RenderPlanGenerator : IIncrementalGenerator
{
    const string Trigger = "CC.CSX.RenderOptimizedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var reports = context.SyntaxProvider.ForAttributeWithMetadataName(
                Trigger,
                predicate: static (n, _) => n is MethodDeclarationSyntax,
                transform: static (ctx, _) => Analyze(ctx))
            .Where(static r => r is not null)
            .Collect();

        context.RegisterSourceOutput(reports, static (spc, all) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> CC.CSX.RenderPlan.Generator — decomposition report (spike)");
            sb.AppendLine("/*");
            foreach (var r in all)
            {
                sb.AppendLine(r!.Text);
                sb.AppendLine();
            }
            sb.AppendLine("*/");
            spc.AddSource("RenderPlan.Decomposition.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    static MethodReport? Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method) return null;
        if (ctx.TargetNode is not MethodDeclarationSyntax decl) return null;
        var ret = ReturnExpression(decl);
        if (ret is null) return new MethodReport(Signature(method), "  (no single return expression — not analyzable)");

        var planner = new Planner(ctx.SemanticModel);
        var segs = Planner.Consolidate(planner.Plan(ret, ImmutableDictionary<string, string>.Empty, 0));
        return new MethodReport(Signature(method), Report.Render(Signature(method), segs));
    }

    static ExpressionSyntax? ReturnExpression(MethodDeclarationSyntax decl)
    {
        if (decl.ExpressionBody is { } eb) return eb.Expression;
        var returns = decl.Body?.Statements.OfType<ReturnStatementSyntax>().ToList();
        return returns is { Count: 1 } ? returns[0].Expression : null;
    }

    static string Signature(IMethodSymbol m)
        => $"{m.Name}({string.Join(", ", m.Parameters.Select(p => $"{p.Type.Name} {p.Name}"))})";
}

internal sealed class MethodReport(string signature, string text)
{
    public string Signature { get; } = signature;
    public string Text { get; } = text;
}

// ---- segment model ----------------------------------------------------------

internal abstract class Segment;
internal sealed class StaticSeg(string text, bool known) : Segment { public string Text = text; public bool Known = known; }
internal sealed class HoleSeg(string expr) : Segment { public string Expr = expr; }
internal sealed class OpaqueSeg(string expr) : Segment { public string Expr = expr; }
internal sealed class LoopSeg(string items, string itemVar, List<Segment> body) : Segment
{ public string Items = items; public string ItemVar = itemVar; public List<Segment> Body = body; }

// ---- the recursive planner --------------------------------------------------

internal sealed class Planner(SemanticModel model)
{
    const int MaxDepth = 48;
    static readonly HashSet<string> ElementType = ["CC.CSX.HtmlElements"];
    static readonly HashSet<string> AttributeTypes = ["CC.CSX.HtmlAttributes", "CC.CSX.Css.CssAttributes", "CC.CSX.Css.CssProperties"];
    static readonly HashSet<string> NonElementFactories = ["Each", "Dyn", "Raw", "Fragment", "None"];

    readonly SemanticModel _model = model;

    public List<Segment> Plan(ExpressionSyntax expr, ImmutableDictionary<string, string> subst, int depth)
    {
        expr = Unwrap(expr);
        if (depth > MaxDepth) return [new OpaqueSeg(Sub(expr, subst))];

        var cv = _model.GetConstantValue(expr);
        if (cv.HasValue) return [new StaticSeg(cv.Value?.ToString() ?? "", known: true)];

        switch (expr)
        {
            case InvocationExpressionSyntax inv: return PlanInvocation(inv, subst, depth);
            case IdentifierNameSyntax or MemberAccessExpressionSyntax: return PlanLeaf(expr, subst);
            default: return [new HoleSeg(Sub(expr, subst))];
        }
    }

    List<Segment> PlanLeaf(ExpressionSyntax expr, ImmutableDictionary<string, string> subst)
    {
        var sym = _model.GetSymbolInfo(expr).Symbol;
        if (sym is IFieldSymbol { IsStatic: true, IsReadOnly: true }) // invariant, value not known at gen time
            return [new StaticSeg($"«{expr}»", known: false)];
        return [new HoleSeg(Sub(expr, subst))];
    }

    List<Segment> PlanInvocation(InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        if (_model.GetSymbolInfo(inv).Symbol is not IMethodSymbol sym)
            return [new OpaqueSeg(Sub(inv, subst))];

        string type = sym.ContainingType?.ToDisplayString() ?? "";

        // unwrap LINQ materializers
        if (type == "System.Linq.Enumerable" && sym.Name is "ToArray" or "ToList" or "AsEnumerable"
            && inv.Expression is MemberAccessExpressionSyntax mat)
            return Plan(mat.Expression, subst, depth);

        // Select(...) and Each(...) -> loops
        if (type == "System.Linq.Enumerable" && sym.Name == "Select" && inv.Expression is MemberAccessExpressionSyntax sel)
            return PlanLoop(sel.Expression, LastArgLambda(inv), subst, depth);
        if (type == "CC.CSX.HtmlElements" && sym.Name == "Each" && inv.ArgumentList.Arguments.Count == 2)
            return PlanLoop(inv.ArgumentList.Arguments[0].Expression, inv.ArgumentList.Arguments[1].Expression, subst, depth);

        // built-in element factory: model by its known rendering
        if (type == "CC.CSX.HtmlElements" && !NonElementFactories.Contains(sym.Name) && ReturnsNode(sym))
            return PlanElement(sym, inv, subst, depth);

        // built-in attribute factory
        if ((AttributeTypes.Contains(type) || IsHtmlPure(sym)) && ReturnsAttribute(sym))
            return PlanAttribute(sym, inv, subst, depth);

        // user pure / render component we can see -> inline (recurse into its body)
        if ((IsHtmlPure(sym) || HasAttr(sym, "CC.CSX.RenderOptimizedAttribute")) && ReturnsNode(sym)
            && TryInline(sym, inv, subst, depth, out var inlined))
            return inlined;

        // boundary: unknown / external / impure call
        return [new OpaqueSeg(Sub(inv, subst))];
    }

    List<Segment> PlanElement(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        string tag = sym.Name.ToLowerInvariant();
        var attrs = new List<Segment>();
        var children = new List<Segment>();
        foreach (var arg in inv.ArgumentList.Arguments)
        {
            var segs = Plan(arg.Expression, subst, depth + 1);
            if (IsAttributeArg(arg.Expression)) attrs.AddRange(segs);
            else children.AddRange(segs);
        }
        var result = new List<Segment> { new StaticSeg($"<{tag}", known: true) };
        result.AddRange(attrs);
        result.Add(new StaticSeg(">", known: true));
        result.AddRange(children);
        result.Add(new StaticSeg($"</{tag}>", known: true));
        return result;
    }

    List<Segment> PlanAttribute(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        string name = sym.Name; // "class", "href", ... (C# @ escaping is not part of the symbol name)
        var result = new List<Segment> { new StaticSeg($" {name}=\"", known: true) };
        if (inv.ArgumentList.Arguments.Count == 1)
            result.AddRange(Plan(inv.ArgumentList.Arguments[0].Expression, subst, depth + 1));
        else
            result.Add(new HoleSeg(Sub(inv, subst)));
        result.Add(new StaticSeg("\"", known: true));
        return result;
    }

    List<Segment> PlanLoop(ExpressionSyntax items, ExpressionSyntax? lambda, ImmutableDictionary<string, string> subst, int depth)
    {
        if (lambda is null) return [new OpaqueSeg(Sub(items, subst))];
        var (param, body) = ExtractLambda(lambda);
        if (body is null) return [new OpaqueSeg(Sub(lambda, subst))];
        // the loop variable is dynamic inside the body; do not substitute it away
        var bodyPlan = Consolidate(Plan(body, subst, depth + 1));
        return [new LoopSeg(Sub(items, subst), param ?? "item", bodyPlan)];
    }

    bool TryInline(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth, out List<Segment> segs)
    {
        segs = [];
        var declRef = sym.DeclaringSyntaxReferences.FirstOrDefault();
        if (declRef?.GetSyntax() is not MethodDeclarationSyntax decl) return false;
        var ret = decl.ExpressionBody?.Expression
                  ?? decl.Body?.Statements.OfType<ReturnStatementSyntax>().SingleOrDefault()?.Expression;
        if (ret is null) return false;

        // bind callee parameters to the call-site argument texts
        var args = inv.ArgumentList.Arguments;
        var bound = subst;
        for (int i = 0; i < sym.Parameters.Length && i < args.Count; i++)
            bound = bound.SetItem(sym.Parameters[i].Name, Sub(args[i].Expression, subst));

        var calleeModel = _model.Compilation.GetSemanticModel(ret.SyntaxTree);
        segs = new Planner(calleeModel).Plan(ret, bound, depth + 1);
        return true;
    }

    // ---- helpers ----

    bool IsAttributeArg(ExpressionSyntax e)
    {
        var t = _model.GetTypeInfo(e).Type;
        if (t is null) return false;
        if (t.IsTupleType) return true; // (key, value) -> attribute
        for (var b = t; b is not null; b = b.BaseType)
            if (b.ToDisplayString() == "CC.CSX.HtmlAttribute") return true;
        return false;
    }

    static bool ReturnsNode(IMethodSymbol m) => Inherits(m.ReturnType, "CC.CSX.HtmlNode") || m.ReturnType.Name == "HtmlNode";
    static bool ReturnsAttribute(IMethodSymbol m) => Inherits(m.ReturnType, "CC.CSX.HtmlAttribute") || m.ReturnType.Name == "HtmlAttribute";
    static bool Inherits(ITypeSymbol? t, string full)
    {
        for (var b = t; b is not null; b = b.BaseType)
            if (b.ToDisplayString() == full) return true;
        return false;
    }
    static bool IsHtmlPure(IMethodSymbol m) => HasAttr(m, "CC.CSX.HtmlPureAttribute");
    static bool HasAttr(IMethodSymbol m, string full)
        => m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == full);

    static ExpressionSyntax Unwrap(ExpressionSyntax e)
        => e is ParenthesizedExpressionSyntax p ? Unwrap(p.Expression) : e;

    static ExpressionSyntax? LastArgLambda(InvocationExpressionSyntax inv)
        => inv.ArgumentList.Arguments.LastOrDefault()?.Expression;

    static (string? param, ExpressionSyntax? body) ExtractLambda(ExpressionSyntax e) => e switch
    {
        SimpleLambdaExpressionSyntax s => (s.Parameter.Identifier.Text, s.ExpressionBody),
        ParenthesizedLambdaExpressionSyntax p => (p.ParameterList.Parameters.FirstOrDefault()?.Identifier.Text, p.ExpressionBody),
        _ => (null, null),
    };

    // best-effort parameter substitution for the report: replace whole-word param names with arg text
    static string Sub(ExpressionSyntax e, ImmutableDictionary<string, string> subst)
    {
        string s = e.ToString();
        foreach (var kv in subst)
            s = Regex.Replace(s, $@"\b{Regex.Escape(kv.Key)}\b", kv.Value.Replace("$", "$$"));
        return s;
    }

    public static List<Segment> Consolidate(List<Segment> segs)
    {
        var outp = new List<Segment>();
        foreach (var s in segs)
        {
            if (s is StaticSeg cur && outp.Count > 0 && outp[outp.Count - 1] is StaticSeg prev)
                prev.Text += cur.Text;
            else
                outp.Add(s);
        }
        return outp;
    }
}

// ---- report rendering -------------------------------------------------------

internal static class Report
{
    public static string Render(string signature, List<Segment> segs)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"  === {signature} ===");
        int statics = 0, holes = 0, loops = 0, opaque = 0;
        Count(segs, ref statics, ref holes, ref loops, ref opaque);
        sb.AppendLine($"  template: {Template(segs)}");
        sb.AppendLine($"  segments: {statics} static, {holes} hole(s), {loops} loop(s), {opaque} opaque");
        sb.AppendLine(opaque == 0
            ? "  verdict : fully decomposable (no opaque boundaries)"
            : $"  verdict : {opaque} opaque boundary(ies) — would render live");
        return sb.ToString();
    }

    static void Count(List<Segment> segs, ref int s, ref int h, ref int l, ref int o)
    {
        foreach (var seg in segs)
            switch (seg)
            {
                case StaticSeg: s++; break;
                case HoleSeg: h++; break;
                case OpaqueSeg: o++; break;
                case LoopSeg loop: l++; Count(loop.Body, ref s, ref h, ref l, ref o); break;
            }
    }

    static string Template(List<Segment> segs)
    {
        var sb = new StringBuilder();
        foreach (var seg in segs)
            sb.Append(seg switch
            {
                StaticSeg st => st.Text,
                HoleSeg hole => "{" + hole.Expr + "}",
                OpaqueSeg op => "{opaque:" + op.Expr + "}",
                LoopSeg loop => "{each " + loop.ItemVar + " in " + loop.Items + ": " + Template(loop.Body) + "}",
                _ => "",
            });
        return sb.ToString();
    }
}
