using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CC.CSX.RenderPlan.Generator;

/// <summary>
/// Finds [RenderOptimized] methods, infers a static/dynamic render plan, and (a) emits a readable
/// decomposition report and (b) generates an optimized writer that bakes static runs to bytes and
/// writes only the dynamic holes/loops. (Spike stage: standalone optimized methods, no interceptors.)
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RenderPlanGenerator : IIncrementalGenerator
{
    const string Trigger = "CC.CSX.RenderOptimizedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plans = context.SyntaxProvider.ForAttributeWithMetadataName(
                Trigger,
                predicate: static (n, _) => n is MethodDeclarationSyntax,
                transform: static (ctx, _) => Analyze(ctx))
            .Where(static p => p is not null)
            .Collect();

        // (a) one combined decomposition report
        context.RegisterSourceOutput(plans, static (spc, all) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> CC.CSX.RenderPlan.Generator — decomposition report");
            sb.AppendLine("/*");
            foreach (var p in all) sb.AppendLine(Report.Render(p!));
            sb.AppendLine("*/");
            spc.AddSource("RenderPlan.Decomposition.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });

        // (b) generated optimized writers, grouped by containing type
        context.RegisterSourceOutput(plans, static (spc, all) =>
        {
            foreach (var group in all.Where(p => p!.Plan is not null)
                                     .GroupBy(p => (p!.Namespace, p.TypeName)))
            {
                var src = CodeEmitter.EmitType(group.Key.Namespace, group.Key.TypeName, group.ToList()!);
                spc.AddSource($"{group.Key.TypeName}__Optimized.g.cs", SourceText.From(src, Encoding.UTF8));
            }
        });
    }

    static MethodPlan? Analyze(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method) return null;
        if (ctx.TargetNode is not MethodDeclarationSyntax decl) return null;

        var ns = method.ContainingNamespace.IsGlobalNamespace ? "" : method.ContainingNamespace.ToDisplayString();
        var typeName = method.ContainingType.Name;
        var pars = method.Parameters
            .Select(p => (Type: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), p.Name))
            .ToList();

        var ret = ReturnExpression(decl);
        if (ret is null)
            return new MethodPlan(ns, typeName, method.Name, pars, null);

        var planner = new Planner(ctx.SemanticModel);
        var segs = Planner.Consolidate(planner.Plan(ret, ImmutableDictionary<string, string>.Empty, 0));
        return new MethodPlan(ns, typeName, method.Name, pars, segs);
    }

    static ExpressionSyntax? ReturnExpression(MethodDeclarationSyntax decl)
    {
        if (decl.ExpressionBody is { } eb) return eb.Expression;
        var returns = decl.Body?.Statements.OfType<ReturnStatementSyntax>().ToList();
        return returns is { Count: 1 } ? returns[0].Expression : null;
    }
}

internal sealed class MethodPlan(string ns, string typeName, string methodName,
    List<(string Type, string Name)> pars, List<Segment>? plan)
{
    public string Namespace { get; } = ns;
    public string TypeName { get; } = typeName;
    public string MethodName { get; } = methodName;
    public List<(string Type, string Name)> Params { get; } = pars;
    public List<Segment>? Plan { get; } = plan;
    public string Signature => $"{MethodName}({string.Join(", ", Params.Select(p => $"{Short(p.Type)} {p.Name}"))})";
    static string Short(string t) { int i = t.LastIndexOf('.'); return i < 0 ? t : t.Substring(i + 1); }
}

// ---- segment model ----------------------------------------------------------

internal enum WriteKind { Text, Value, Node }

internal abstract class Segment;
internal sealed class StaticSeg(string text) : Segment { public string Text = text; }
internal sealed class HoleSeg(string expr, WriteKind kind) : Segment { public string Expr = expr; public WriteKind Kind = kind; }
internal sealed class OpaqueSeg(string expr, WriteKind kind) : Segment { public string Expr = expr; public WriteKind Kind = kind; }
internal sealed class LoopSeg(string items, string itemVar, List<Segment> body) : Segment
{ public string Items = items; public string ItemVar = itemVar; public List<Segment> Body = body; }

// ---- recursive planner ------------------------------------------------------

internal sealed class Planner(SemanticModel model)
{
    const int MaxDepth = 48;
    static readonly HashSet<string> AttributeTypes = ["CC.CSX.HtmlAttributes", "CC.CSX.Css.CssAttributes", "CC.CSX.Css.CssProperties"];
    static readonly HashSet<string> NonElementFactories = ["Each", "Dyn", "Raw", "Fragment", "None"];

    readonly SemanticModel _model = model;

    public List<Segment> Plan(ExpressionSyntax expr, ImmutableDictionary<string, string> subst, int depth)
    {
        expr = Unwrap(expr);
        if (depth > MaxDepth) return [new OpaqueSeg(Sub(expr, subst), KindOf(expr))];

        var cv = _model.GetConstantValue(expr);
        if (cv.HasValue) return [new StaticSeg(cv.Value?.ToString() ?? "")];

        switch (expr)
        {
            case InvocationExpressionSyntax inv: return PlanInvocation(inv, subst, depth);
            case IdentifierNameSyntax or MemberAccessExpressionSyntax: return PlanLeaf(expr, subst);
            default: return [new HoleSeg(Sub(expr, subst), KindOf(expr))];
        }
    }

    List<Segment> PlanLeaf(ExpressionSyntax expr, ImmutableDictionary<string, string> subst)
    {
        if (_model.GetSymbolInfo(expr).Symbol is IFieldSymbol { IsStatic: true, IsReadOnly: true })
            return [new StaticSeg($"«{expr}»")]; // invariant; value not known at gen time (report-only)
        return [new HoleSeg(Sub(expr, subst), KindOf(expr))];
    }

    List<Segment> PlanInvocation(InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        if (_model.GetSymbolInfo(inv).Symbol is not IMethodSymbol sym)
            return [new OpaqueSeg(Sub(inv, subst), WriteKind.Node)];

        string type = sym.ContainingType?.ToDisplayString() ?? "";

        if (type == "System.Linq.Enumerable" && sym.Name is "ToArray" or "ToList" or "AsEnumerable"
            && inv.Expression is MemberAccessExpressionSyntax mat)
            return Plan(mat.Expression, subst, depth);

        if (type == "System.Linq.Enumerable" && sym.Name == "Select" && inv.Expression is MemberAccessExpressionSyntax sel)
            return PlanLoop(sel.Expression, LastArgLambda(inv), subst, depth);
        if (type == "CC.CSX.HtmlElements" && sym.Name == "Each" && inv.ArgumentList.Arguments.Count == 2)
            return PlanLoop(inv.ArgumentList.Arguments[0].Expression, inv.ArgumentList.Arguments[1].Expression, subst, depth);

        if (type == "CC.CSX.HtmlElements" && !NonElementFactories.Contains(sym.Name) && ReturnsNode(sym))
            return PlanElement(sym, inv, subst, depth);

        if ((AttributeTypes.Contains(type) || IsHtmlPure(sym)) && ReturnsAttribute(sym))
            return PlanAttribute(sym, inv, subst, depth);

        if ((IsHtmlPure(sym) || HasAttr(sym, "CC.CSX.RenderOptimizedAttribute")) && ReturnsNode(sym)
            && TryInline(sym, inv, subst, depth, out var inlined))
            return inlined;

        return [new OpaqueSeg(Sub(inv, subst), KindOf(inv))];
    }

    List<Segment> PlanElement(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        string tag = sym.Name.ToLowerInvariant();
        var attrs = new List<Segment>();
        var children = new List<Segment>();
        foreach (var arg in inv.ArgumentList.Arguments)
        {
            var segs = Plan(arg.Expression, subst, depth + 1);
            (IsAttributeArg(arg.Expression) ? attrs : children).AddRange(segs);
        }
        var result = new List<Segment> { new StaticSeg($"<{tag}") };
        result.AddRange(attrs);
        result.Add(new StaticSeg(">"));
        result.AddRange(children);
        result.Add(new StaticSeg($"</{tag}>"));
        return result;
    }

    List<Segment> PlanAttribute(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth)
    {
        var result = new List<Segment> { new StaticSeg($" {sym.Name}=\"") };
        if (inv.ArgumentList.Arguments.Count == 1)
            result.AddRange(Plan(inv.ArgumentList.Arguments[0].Expression, subst, depth + 1));
        else
            result.Add(new HoleSeg(Sub(inv, subst), WriteKind.Text));
        result.Add(new StaticSeg("\""));
        return result;
    }

    List<Segment> PlanLoop(ExpressionSyntax items, ExpressionSyntax? lambda, ImmutableDictionary<string, string> subst, int depth)
    {
        if (lambda is null) return [new OpaqueSeg(Sub(items, subst), WriteKind.Node)];
        var (param, body) = ExtractLambda(lambda);
        if (body is null) return [new OpaqueSeg(Sub(lambda, subst), WriteKind.Node)];
        return [new LoopSeg(Sub(items, subst), param ?? "item", Consolidate(Plan(body, subst, depth + 1)))];
    }

    bool TryInline(IMethodSymbol sym, InvocationExpressionSyntax inv, ImmutableDictionary<string, string> subst, int depth, out List<Segment> segs)
    {
        segs = [];
        if (sym.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is not MethodDeclarationSyntax decl) return false;
        var ret = decl.ExpressionBody?.Expression
                  ?? decl.Body?.Statements.OfType<ReturnStatementSyntax>().SingleOrDefault()?.Expression;
        if (ret is null) return false;

        var args = inv.ArgumentList.Arguments;
        var bound = subst;
        for (int i = 0; i < sym.Parameters.Length && i < args.Count; i++)
            bound = bound.SetItem(sym.Parameters[i].Name, Sub(args[i].Expression, subst));

        var calleeModel = _model.Compilation.GetSemanticModel(ret.SyntaxTree);
        segs = new Planner(calleeModel).Plan(ret, bound, depth + 1);
        return true;
    }

    // ---- helpers ----

    WriteKind KindOf(ExpressionSyntax e)
    {
        var t = _model.GetTypeInfo(e).Type;
        if (t is null) return WriteKind.Text;
        if (t.SpecialType == SpecialType.System_String) return WriteKind.Text;
        if (Inherits(t, "CC.CSX.HtmlNode") || Inherits(t, "CC.CSX.HtmlItem")) return WriteKind.Node;
        return WriteKind.Value;
    }

    bool IsAttributeArg(ExpressionSyntax e)
    {
        var t = _model.GetTypeInfo(e).Type;
        if (t is null) return false;
        if (t.IsTupleType) return true;
        return Inherits(t, "CC.CSX.HtmlAttribute");
    }

    static bool ReturnsNode(IMethodSymbol m) => Inherits(m.ReturnType, "CC.CSX.HtmlNode") || m.ReturnType.Name == "HtmlNode";
    static bool ReturnsAttribute(IMethodSymbol m) => Inherits(m.ReturnType, "CC.CSX.HtmlAttribute") || m.ReturnType.Name == "HtmlAttribute";
    static bool Inherits(ITypeSymbol? t, string full)
    {
        for (var b = t; b is not null; b = b.BaseType)
            if (b.ToDisplayString() == full) return true;
        return false;
    }
    static bool IsHtmlPure(IMethodSymbol m) => HasAttr(m, "CC.CSX.HtmlPureAttribute");
    static bool HasAttr(IMethodSymbol m, string full) => m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == full);

    static ExpressionSyntax Unwrap(ExpressionSyntax e) => e is ParenthesizedExpressionSyntax p ? Unwrap(p.Expression) : e;
    static ExpressionSyntax? LastArgLambda(InvocationExpressionSyntax inv) => inv.ArgumentList.Arguments.LastOrDefault()?.Expression;

    static (string? param, ExpressionSyntax? body) ExtractLambda(ExpressionSyntax e) => e switch
    {
        SimpleLambdaExpressionSyntax s => (s.Parameter.Identifier.Text, s.ExpressionBody),
        ParenthesizedLambdaExpressionSyntax p => (p.ParameterList.Parameters.FirstOrDefault()?.Identifier.Text, p.ExpressionBody),
        _ => (null, null),
    };

    static string Sub(ExpressionSyntax e, ImmutableDictionary<string, string> subst)
    {
        string s = e.ToString();
        foreach (var kv in subst)
            s = Regex.Replace(s, $@"\b{Regex.Escape(kv.Key)}\b", kv.Value.Replace("$", "$$"));
        return s;
    }

    public static List<Segment> Consolidate(List<Segment> segs)
    {
        var outp = new List<Segment>();
        foreach (var s in segs)
        {
            if (s is StaticSeg cur && outp.Count > 0 && outp[outp.Count - 1] is StaticSeg prev) prev.Text += cur.Text;
            else outp.Add(s);
        }
        return outp;
    }
}
