#!/usr/bin/env python3
"""Regenerate src/CC.CSX/CssPropertyKeys.cs from MDN's css property data.

Sources, merged:
  - https://raw.githubusercontent.com/mdn/data/main/css/properties.json (status == standard)
  - the existing CssPropertyKeys.cs (preserves descriptions, at-rules and legacy entries)

Run from the repo root, then run eng/gen-css-properties.py to refresh CssProperties.cs.
"""
import json, re, sys, urllib.request

MDN_URL = "https://raw.githubusercontent.com/mdn/data/main/css/properties.json"
KEYS_PATH = "src/CC.CSX/CssPropertyKeys.cs"
# known mistakes in the historic list: never emit these
DROP = {"hypenate-character"}  # typo of hyphenate-character


def to_const_name(css_name: str) -> str:
    segments = re.split(r"[-_@]", css_name)
    return "".join(s[:1].upper() + s[1:] for s in segments if s)


def xml_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main() -> None:
    existing_src = open(KEYS_PATH).read()
    existing = {
        name: doc.strip()
        for doc, _, name in re.findall(
            r"///(.*?)\n\s*///</summary>\s*\n\s*public const string @(\w+) = \"([^\"]+)\";",
            existing_src,
        )
    }

    if len(sys.argv) > 1:
        mdn = json.load(open(sys.argv[1]))
    else:
        with urllib.request.urlopen(MDN_URL) as response:
            mdn = json.load(response)

    merged: dict[str, str] = {}
    for name, info in sorted(mdn.items()):
        if info.get("status") != "standard" or name.startswith("--"):
            continue
        if name in existing:
            merged[name] = existing[name]
        else:
            groups = info.get("groups") or []
            group = f"{groups[0]} property." if groups else "CSS property."
            url = info.get("mdn_url", "")
            doc = f" {name}\t{xml_escape(group)}" + (f" See {url}" if url else "")
            merged[name] = doc
    # keep historic entries MDN no longer lists as standard (legacy props, at-rules)
    for name, doc in existing.items():
        if name not in merged and name not in DROP:
            merged[name] = doc

    out = ["namespace CC.CSX;", ""]
    out.append("///<summary>")
    out.append("/// A list of all available css properties")
    out.append("/// (generated by eng/gen-css-property-keys.py from MDN data — regenerate, don't hand-edit)")
    out.append("/// </summary>")
    out.append("public static class CssPropertyKeys")
    out.append("{")
    first = True
    for name in sorted(merged, key=to_const_name):
        if not first:
            out.append("")
        first = False
        out.append("    ///<summary>")
        out.append(f"    ///{merged[name]}")
        out.append("    ///</summary>")
        out.append(f'    public const string @{to_const_name(name)} = "{name}";')
    out.append("}")

    with open(KEYS_PATH, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"emitted {len(merged)} constants ({len(merged) - len(existing)} net new)")


if __name__ == "__main__":
    main()
