#!/usr/bin/env python3
"""Generate src/CC.CSX.Browser/HtmlEvents.g.cs from HtmlElementEventKeys.

Reads the event key constants in src/CC.CSX/HtmlAttributeKeys_Events.cs
(e.g. onClick = "onclick") and emits delegate-based overloads
(onClick(Action), onClick(Action<DomEvent>), async variants) that bind to
the CC.CSX.Browser event registry. Run from the repo root:

    python3 eng/gen-browser-events.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src/CC.CSX/HtmlAttributeKeys_Events.cs"
TARGET = ROOT / "src/CC.CSX.Browser/HtmlEvents.g.cs"

SIGNATURES = ["Action", "Action<DomEvent>", "Func<Task>", "Func<DomEvent, Task>"]

def main():
    text = SOURCE.read_text()
    events = re.findall(r'public const string (\w+) = "(\w+)";', text)
    if not events:
        raise SystemExit(f"no event constants found in {SOURCE}")

    lines = [
        "// <auto-generated>",
        "// Generated by eng/gen-browser-events.py from src/CC.CSX/HtmlAttributeKeys_Events.cs.",
        "// Do not edit by hand — regenerate instead.",
        "// </auto-generated>",
        "using System;",
        "using System.Threading.Tasks;",
        "using CC.CSX;",
        "",
        "namespace CC.CSX.Browser;",
        "",
        "public static partial class HtmlEvents",
        "{",
    ]
    for name, attr in events:
        dom = attr.removeprefix("on")  # "onclick" -> "click"
        for sig in SIGNATURES:
            lines.append(f"    ///<summary>Handles the '{dom}' DOM event with a .NET handler.</summary>")
            lines.append(f'    public static HtmlAttribute {name}({sig} handler) => Bind("{dom}", handler);')
            lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"wrote {TARGET} ({len(events)} events x {len(SIGNATURES)} overloads)")

if __name__ == "__main__":
    main()
