#!/usr/bin/env python3
"""One-off: generate CssProperties.cs (lowercase factory methods) from CssPropertyKeys.cs."""
import re, sys

KEYWORDS = {
    "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
    "continue","decimal","default","delegate","do","double","else","enum","event","explicit",
    "extern","false","finally","fixed","float","for","foreach","goto","if","implicit","in","int",
    "interface","internal","is","lock","long","namespace","new","null","object","operator","out",
    "override","params","private","protected","public","readonly","ref","return","sbyte","sealed",
    "short","sizeof","stackalloc","static","string","struct","switch","this","throw","true","try",
    "typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual","void","volatile","while",
}

src = open("src/CC.CSX/CssPropertyKeys.cs").read()
pattern = re.compile(
    r"///<summary>\s*\n\s*///(.*?)\n\s*///</summary>\s*\n\s*public const string @(\w+) = \"([^\"]+)\";"
)
matches = pattern.findall(src)
if not matches:
    sys.exit("no constants matched")

out = []
out.append("""// <auto-generated>
// Generated from CssPropertyKeys.cs by eng/gen-css-properties.py. Do not edit by hand.
// </auto-generated>
namespace CC.CSX.Css;

///<summary>
/// Strongly typed, lowercase factory methods for every CSS property — one per
/// <see cref="CssPropertyKeys"/> constant. Intended for <c>using static CC.CSX.Css.CssProperties;</c>.
/// Lowercase by convention: elements are PascalCase, styles/classes are lowercase.
///</summary>
public static class CssProperties
{""")

matches = [m for m in matches if not m[2].startswith("@")]  # at-rules (@charset, @media, ...) are not inline-style properties

for doc, const_name, css_name in matches:
    camel = const_name[0].lower() + const_name[1:]
    if camel in KEYWORDS:
        camel = "@" + camel
    out.append(f"    ///<summary>")
    out.append(f"    ///{doc}")
    out.append(f"    ///</summary>")
    out.append(f"    public static CssDeclaration {camel}(string value) => new(CssPropertyKeys.@{const_name}, value);")
out.append("}")

with open("src/CC.CSX.Css/CssProperties.cs", "w") as f:
    f.write("\n".join(out) + "\n")
print(f"generated {len(matches)} property methods")
