using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CC.CSX.Css.Generator;

/// <summary>
/// Incremental generator that turns every <c>.css</c> file registered as an
/// <c>AdditionalFiles</c> item into strongly typed members:
/// <code>
/// // styles/app.css with .card and .card--highlighted produces:
/// Css.App.card, Css.App.cardHighlighted   // CssClass constants
/// Css.App.Source                          // the stylesheet text baked into the assembly
/// Css.App.Bundle                          // CssBundle (name + content + hash)
/// </code>
/// The generated code lives in the project's root namespace.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CssClassesGenerator : IIncrementalGenerator
{
    static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns)
                && !string.IsNullOrWhiteSpace(ns) ? ns : null)
            .Combine(context.CompilationProvider.Select((c, _) => c.AssemblyName))
            .Select((pair, _) => pair.Left ?? pair.Right ?? "CC.CSX.Css.Generated");

        var cssFiles = context.AdditionalTextsProvider
            .Where(text => text.Path.EndsWith(".css", StringComparison.OrdinalIgnoreCase))
            .Select((text, ct) => (text.Path, Content: text.GetText(ct)?.ToString()))
            .Where(file => file.Content is not null);

        context.RegisterSourceOutput(cssFiles.Combine(rootNamespace), static (spc, input) =>
        {
            var ((path, content), ns) = input;
            var fileName = Path.GetFileNameWithoutExtension(path);
            var className = ToPascalIdentifier(fileName);
            var source = GenerateSource(ns, className, fileName, content!);
            spc.AddSource($"Css.{className}.{StableHash(path)}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    static string GenerateSource(string ns, string className, string bundleName, string css)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Strongly typed CSS generated from the project's stylesheets.</summary>");
        sb.AppendLine("    public static partial class Css");
        sb.AppendLine("    {");
        sb.AppendLine($"        /// <summary>Typed classes for <c>{bundleName}.css</c>.</summary>");
        sb.AppendLine($"        public static partial class {className}");
        sb.AppendLine("        {");

        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var cssName in CssScanner.ExtractClassNames(css))
        {
            var identifier = CssScanner.ToCSharpIdentifier(cssName);
            if (CSharpKeywords.Contains(identifier))
                identifier = "@" + identifier;
            var unique = identifier;
            for (int suffix = 2; !used.Add(unique); suffix++)
                unique = $"{identifier}_{suffix}";
            sb.AppendLine($"            /// <summary><c>.{cssName}</c></summary>");
            sb.AppendLine($"            public static readonly global::CC.CSX.Css.CssClass {unique} = new global::CC.CSX.Css.CssClass(\"{cssName}\");");
        }

        sb.AppendLine();
        sb.AppendLine("            /// <summary>The raw stylesheet text, baked into the assembly.</summary>");
        sb.AppendLine($"            public const string Source = @\"{css.Replace("\"", "\"\"")}\";");
        sb.AppendLine();
        sb.AppendLine("            /// <summary>The stylesheet as a composable bundle.</summary>");
        sb.AppendLine($"            public static readonly global::CC.CSX.Css.CssBundle Bundle = new global::CC.CSX.Css.CssBundle(\"{bundleName}\", Source);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>PascalCase for the container class (types follow node casing).</summary>
    static string ToPascalIdentifier(string name)
    {
        var identifier = CssScanner.ToCSharpIdentifier(name.Replace(".", "-"));
        return identifier.Length == 0 || identifier == "_"
            ? "Styles"
            : char.ToUpperInvariant(identifier[0]) + identifier.Substring(1);
    }

    /// <summary>Deterministic FNV-1a hash so two same-named css files in different folders get distinct hint names.</summary>
    static string StableHash(string value)
    {
        unchecked
        {
            uint hash = 2166136261;
            foreach (char c in value)
                hash = (hash ^ c) * 16777619;
            return hash.ToString("x8");
        }
    }
}
